<?php
/**
 * Date: 07.10.12
 * Time: 1:14
 * Author: Ivan Voskoboynyk
 */
class AxisExtendsBehaviorSubclassStubBuilder extends PHP5ExtensionObjectBuilder
{
  const HOST_BEHAVIOR_NAME = 'axis_extends';

  public $overwrite = false;

  public function getPackage()
  {
    return $this->getTable()->getBehavior(static::HOST_BEHAVIOR_NAME)->getParameter('package') ?: parent::getPackage();
  }
  /**
   * Returns the qualified (prefixed) classname that is being built by the current class.
   * This method must be implemented by child classes.
   * @return string
   */
  public function getUnprefixedClassname()
  {
    return $this->getTable()->getBehavior(static::HOST_BEHAVIOR_NAME)->getParameter('class_name');
  }

  protected function addIncludes(&$script)
  {
    // nothing?
    // TODO: Add includes
  }

  protected function addClassOpen(&$script)
  {
    $table = $this->getTable();
    $this->declareClassFromBuilder($this->getObjectBuilder());
    $tableName = $table->getName();
    $tableDesc = $table->getDescription();

    $baseTableName = $this->getTable()->getBehavior(static::HOST_BEHAVIOR_NAME)->getParameter('extends');
    $baseClassname = 'Base'.$this->getClassname();

    $script .= "

/**
 * Skeleton subclass for representing a row from the '$tableName' table.
 *
 * $tableDesc
 *";
    if ($this->getBuildProperty('addTimeStamp')) {
      $now = strftime('%c');
      $script .= "
 * This class was autogenerated by Propel " . $this->getBuildProperty('version') . " on:
 *
 * $now
 *";
    }
    $script .= "
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.".$this->getPackage()."
 */
".($table->isAbstract() ? "abstract " : "")."class ".$this->getClassname()." extends $baseClassname {
";
  }
}
