<?php
/**
 * Date: 07.10.12
 * Time: 1:14
 * Author: Ivan Voskoboynyk
 */
class AxisExtendsBehaviorQueryStubBuilder extends OMBuilder
{
  const HOST_BEHAVIOR_NAME = 'axis_extends';
  /**
   * Returns the qualified (prefixed) classname that is being built by the current class.
   * This method must be implemented by child classes.
   * @return string
   */
  public function getUnprefixedClassname()
  {
    return $this->getTable()->getBehavior(static::HOST_BEHAVIOR_NAME)->getParameter('class_name').'Query';
  }

  protected function addClassOpen(&$script)
  {
    $baseTableName = $this->getTable()->getBehavior(static::HOST_BEHAVIOR_NAME)->getParameter('extends');

    $script .= "

/**
 * Skeleton subclass for representing a query for one of the subclasses of the '$baseTableName' table.
 *";
if ($this->getBuildProperty('addTimeStamp')) {
$now = strftime('%c');
$script .= "
 * This class was autogenerated by Propel {$this->getBuildProperty('version')} on:
 *
 * $now
 *";
}
$script .= "
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.{$this->getPackage()}
 */
class {$this->getClassname()} extends Base{$this->getClassname()} {

";
  }

  protected function addClassBody(& $script)
  {
  }

  protected function addClassClose(&$script)
  {
    $script .= "
} // " . $this->getClassname() . "
";
  }
}
